name: CI & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: "Run lint and format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Set Go version and paths"
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"

      - name: "Check and lint code"
        run: |
          make lint

      - name: "Run build"
        run: |
          make build
