name: Release Assets

on:
  release:
    types: [published]

env:
  DOCKER_USER: bencuk
  IMAGE_NAME: kubeview

jobs:
  release:
    name: Release image & chart
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Set Go version and paths"
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"

      - name: "Run build"
        run: |
          make build

      - name: "Upload binary to release"
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/locust-reporter
          asset_name: locust-reporter
          asset_content_type: application/octet-stream
